### ISSUE TITLE
Bug: grabbing issue

### ISSUE THREAD

**Issue by RICEFARMINGPANDA** [ChildrenOfYahweh/Kematian-Stealer#206]
### What Did You Expect To Happen?

i expected the program to grab information

### What Happened?

while testing if the batch file works it says vps/vm/vpn is not allowed! but i dont have any of those running

### Add Screenshots

![Screenshot 2024-05-15 205045](https://github.com/ChildrenOfYahweh/Kematian-Stealer/assets/156966015/f3856f97-7dd7-441e-96a9-7698901338aa)
![Screenshot 2024-05-15 205045](https://github.com/ChildrenOfYahweh/Kematian-Stealer/assets/156966015/f3856f97-7dd7-441e-96a9-7698901338aa)
![Screenshot 2024-05-15 205045](https://github.com/ChildrenOfYahweh/Kematian-Stealer/assets/156966015/f3856f97-7dd7-441e-96a9-7698901338aa)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [X] I have attempted to resolve my problem by myself

**Comment by KDot227** [comment]
> ### What Did You Expect To Happen?
> 
> i expected the program to grab information
> 
> ### What Happened?
> 
> while testing if the batch file works it says vps/vm/vpn is not allowed! but i dont have any of those running
> 
> ### Add Screenshots
> 
> ![Screenshot 2024-05-15 205045](https://github.com/ChildrenOfYahweh/Kematian-Stealer/assets/156966015/f3856f97-7dd7-441e-96a9-7698901338aa)
> 
> ![Screenshot 2024-05-15 205045](https://github.com/ChildrenOfYahweh/Kematian-Stealer/assets/156966015/f3856f97-7dd7-441e-96a9-7698901338aa)
> 
> ![Screenshot 2024-05-15 205045](https://github.com/ChildrenOfYahweh/Kematian-Stealer/assets/156966015/f3856f97-7dd7-441e-96a9-7698901338aa)
> 
> 
> 
> ### Check the following before submitting (If Applicable)
> 
> - [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> - [X] I have attempted to resolve my problem by myself

I will add error type into the message in 2 hours so you can see exactly what it is. You're getting this error for 1 of a few reasons.

- Not enough ram on your pc (less than 4gb I think
- You have a blacklisted username

**Comment by RICEFARMINGPANDA** [comment]
oh, i have 8gb of ram but i dont remember ever being blacklisted from ur software is there any other reasons why and how could i resolve it?

**Comment by KDot227** [comment]
> oh, i have 8gb of ram but i dont remember ever being blacklisted from ur software is there any other reasons why and how could i resolve it?

I will change the repo to print the issue along with the error when you run it. Once I do it wait like 30 seconds to 5 minutes then rerun the program.

**Comment by KDot227** [comment]
@RICEFARMINGPANDA can you try again?

**Comment by RICEFARMINGPANDA** [comment]
new issue now
![Uploading Screenshot 2024-05-18 094407.png…]()

**Comment by KDot227** [comment]
I can't see the image

**Comment by RICEFARMINGPANDA** [comment]
![Screenshot 2024-05-18 094407](https://github.com/ChildrenOfYahweh/Kematian-Stealer/assets/156966015/6802f541-c002-42bc-8ef5-cdb9a8ff4192)

**Comment by KDot227** [comment]
> ![Screenshot 2024-05-18 094407](https://private-user-images.githubusercontent.com/156966015/331750213-6802f541-c002-42bc-8ef5-cdb9a8ff4192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5OTAwMjIsIm5iZiI6MTcxNTk4OTcyMiwicGF0aCI6Ii8xNTY5NjYwMTUvMzMxNzUwMjEzLTY4MDJmNTQxLWMwMDItNDJiYy04ZWY1LWNkYjlhOGZmNDE5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QyMzQ4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWJhNTlhNjczYmVjZDc3NjA2YmU2MTZmMGM3OTIwMjFjNjkzOTk0OTc1N2RiOTEyOGE0ZGM5MTcwOTMwZjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sPtEVLeAG4ejYVTEYx4ZLuQQsDn4vOJfrUQTSIjXLLw)

fake error. I forgot to turn the option off.

**Comment by RICEFARMINGPANDA** [comment]
i have the original issue now lol

**Comment by KDot227** [comment]
> i have the original issue now lol

does it say the type of error now though?

**Comment by RICEFARMINGPANDA** [comment]
no not really, it just says vps/vm/vpn not allowed

**Comment by KDot227** [comment]
> no not really, it just says vps/vm/vpn not allowed

Add me on discord kdot_227
