### ISSUE TITLE
Keep up good work brother!

### ISSUE THREAD

**Issue by xxopenxx** [ChildrenOfYahweh/Kematian-Stealer#235]
### What Feature?

Great stealer, great updates. Keep it up. 
Waiting for more features :)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [ ] I want to work on this feature

**Comment by KDot227** [comment]
> ### What Feature?
> 
> Great stealer, great updates. Keep it up. Waiting for more features :)
> ### Add Screenshots (If Applicable)
> 
> _No response_
> ### Check the following before submitting (If Applicable)
> 
>     * [x]  I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> 
>     * [ ]  I want to work on this feature

Thank you
