### ISSUE TITLE
malaware 

### ISSUE THREAD

**Issue by sxury999** [ChildrenOfYahweh/Kematian-Stealer#236]
### What Feature?

to the people saying its a 10 you are prolly apart of a botnet
![Screenshot 2024-06-02 085641](https://github.com/ChildrenOfYahweh/Kematian-Stealer/assets/170886134/570a5d6a-3d17-4dd3-9bbe-d1208129f6a5)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [X] I want to work on this feature

**Comment by KDot227** [comment]
> ### What Feature?
> 
> to the people saying its a 10 you are prolly apart of a botnet
> 
> ![Screenshot 2024-06-02 085641](https://github.com/ChildrenOfYahweh/Kematian-Stealer/assets/170886134/570a5d6a-3d17-4dd3-9bbe-d1208129f6a5)
> 
> 
> 
> ### Add Screenshots (If Applicable)
> 
> _No response_
> 
> ### Check the following before submitting (If Applicable)
> 
> - [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> - [X] I want to work on this feature

Bro what 💀. What did you even scan.

**Comment by KDot227** [comment]
Also literally every aspect of the entire project is open source. Anything in releases is uploaded by GitHub actions. I've never touched a single file in releases. You can very easily read the code before making an issue claiming I'm making a "botnet". Even if I did I would be trying to profit off kids like you who have no conceptuality or understanding of how the project actually works which makes me assume your a dumb 8th grader who got a pc for his birthday and is trying to be super man. Thank you for using my software.
