### ISSUE TITLE
Bug: Very Late injection

### ISSUE THREAD

**Issue by Agonyxxx** [ChildrenOfYahweh/Kematian-Stealer#243]
### What Did You Expect To Happen?

Instant injection and sent to webhook

### What Happened?

i had to wait 1 hour for the stealer to send 

### Add Screenshots

none

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [X] I have attempted to resolve my problem by myself

**Comment by KDot227** [comment]
> ### What Did You Expect To Happen?
> 
> Instant injection and sent to webhook
> ### What Happened?
> 
> i had to wait 1 hour for the stealer to send
> ### Add Screenshots
> 
> none
> ### Check the following before submitting (If Applicable)
> 
>     * [x]  I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> 
>     * [x]  I have attempted to resolve my problem by myself

In the builder can you press debug and test and find what part it gets stuck on?
